### ISSUE TITLE
Some escape characters have a probability of not being recognized

### ISSUE THREAD

**Issue by ZhaoZhiqiao** [symlPigeon/YPMDL#4]
Many thanks to the author for this project, but when I use this project, I find that there is a certain probability that the escape symbol cannot be correctly recognized, such as "\t". I think this is a bug and hope the author will fix it in the next release. Finally, best wishes to the author, thanks to the author's open source spirit and selfless dedication.
The following is the place where I think there is a problem and the song is [コクハクワープ]
![image](https://github.com/symlPigeon/YADL/assets/53613487/d599aa07-80ce-4670-80a5-3e3bd1d31d45)
The following is my os configuration
![image](https://github.com/symlPigeon/YADL/assets/53613487/9323da03-1328-4e21-9a44-5f5538315c26)

**Comment by symlPigeon** [comment]
Fixed in #5 .

**Comment by symlPigeon** [comment]
Another related issue was fixed in #6 .
